### PR TITLE
Issue/148

### LINKED ISSUE #148: REST API: register_rest_route called incorrectly
I expect to not have PHP notices when I'm editing a post in the block editor, but with Slack active, I get:

> PHP Notice:  register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>edd-slack/v1/slack-app/interactive-message/submit</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.)
> PHP Notice:  register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>edd-slack/v1/slack-app/slash-command/submit</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.)

### PR DESCRIPTION
**Pull request by rwebster85**
Fixes #148

Proposed Changes:
1. Added `'permission_callback' => '__return_true'` to the `register_rest_route()` function calls, since they are public routes.

### CODE REVIEW

File: core/ssl-only/class-edd-slack-ssl-rest.php [hunk 1]
```diff
@@ -38,12 +38,14 @@ public function create_routes() {
...
 			'methods' => 'POST',
 			'callback' => array( $this, 'route_interactive_message' ),
+			'permission_callback' => '__return_true'
 		) );
 
 		// REST Route for /edd Slash Command
 		register_rest_route( 'edd-slack/v1', '/slack-app/slash-command/submit', array(
 			'methods' => 'POST',
 			'callback' => array( $this, 'route_slash_command' ),
+			'permission_callback' => '__return_true'
```
Comment (ashleyfae) [inline core/ssl-only/class-edd-slack-ssl-rest.php:48]: This looks good, but can you reformat the array to make the parameters line up now that there's a longer one? Here's an example that shows how we like it: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-fees.php#L68-L76 (note how the `=>` are all aligned)

Comment (rwebster85) [reply core/ssl-only/class-edd-slack-ssl-rest.php:48]: Done :)

**Review by robincornett — APPROVED** [review]
