### PR TITLE
Fix edd_slack_get_users errors, constant pinging

### LINKED ISSUE #129: PHP Notice/Warning when linking Slack
When I linked my site to Slack, I got the following notice and warning:

```
PHP Notice:  Undefined property: stdClass::$members in \wp-content\plugins\edd-slack\core\edd-slack-functions.php on line 42
PHP Warning:  Invalid argument supplied for foreach() in \wp-content\plugins\edd-slack\core\edd-slack-functions.php on line 45
```

This is with the master branch, EDD 2.10.2, WP 5.7.

Noting also that the `https://slack.com/api/users.list` request is running pretty much constantly, which doesn't seem good.

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #129

Proposed changes:
1. Adds a check for ajax--this may not be truly necessary but if you use a plugin like Log HTTP Requests, you can see this API request runs an awful lot.
2. Rearranges some logic for checking the transient value.
3. Does not use `$result->members` if it's empty.

### CODE REVIEW

**Review by LisaCee — APPROVED** [review]
I couldn't duplicate your original issue, but this looks good to me.

**Comment by mihaijoldis** [comment]
@robincornett I can confirm this fixed the issue for me during testing.

File: core/edd-slack-functions.php [hunk 1]
```diff
@@ -24,73 +24,90 @@ function EDDSLACK() {
...
- * @since		1.1.0
- * @return		array Slack Users
+ *
+ * @since   1.1.0
+ * @return  array Slack Users
  */
 function edd_slack_get_users() {
-	
+
+	if ( wp_doing_ajax() ) {
```
Comment (ashleyfae) [inline core/edd-slack-functions.php:33]: Let's add a `function_exists()` check here. `wp_doing_ajax()` was introduced in 4.7, and it looks like we claim to support back to 4.4.

File: core/edd-slack-functions.php [hunk 2]
```diff
@@ -24,73 +24,90 @@ function EDDSLACK() {
...
+		return array();
+	}
+	$transient = get_transient( 'edd_slack_users' );
+	if ( $transient ) {
+		return $transient;
```
Comment (ashleyfae) [inline core/edd-slack-functions.php:38]: Does this need `maybe_unserialize()` around it? It was used in the old code, though I don't know that it's actually necessary.

File: core/edd-slack-functions.php [hunk 3]
```diff
@@ -24,73 +24,90 @@ function EDDSLACK() {
...
 
 	// Don't bother if we don't have an OAUTH Token
-	if ( ! $oauth_token || $oauth_token == '-1' ) return array();
+	if ( ! $oauth_token || '-1' == $oauth_token ) {
+		return array();
+	}
 
-	if ( ! $users_array = maybe_unserialize( get_transient( 'edd_slack_users' ) ) ) {
+	$users_array = maybe_unserialize( $transient );
+	if ( ! $users_array ) {
```
Comment (ashleyfae) [inline core/edd-slack-functions.php:49]: I'm pretty sure this:

```php
$users_array = maybe_unserialize( $transient );
```

and the `if ( ! $users_array )` after can go away now that you have the early return at the top.

File: core/edd-slack-functions.php [hunk 4]
```diff
@@ -24,73 +24,90 @@ function EDDSLACK() {
...
 
 		$result = EDDSLACK()->slack_api->get( 'users.list' );
 
+		if ( empty( $result->members ) ) {
+			return array();
```
Comment (ashleyfae) [inline core/edd-slack-functions.php:54]: Should we be setting the transient here? Otherwise if you have no members it will still be doing a fresh API request each time.

Comment (robincornett) [reply core/edd-slack-functions.php]: I'm thinking not to set the transient here, because if you have no users and then add one, but the transient hasn't expired, the user list won't have updated.

To be honest, I'm not sure the transient is needed if this is set up correctly, which I don't think it was. One of the reasons for the transient, I suspect, is that `edd_slack_get_users` was hooked into `admin_init`, so it was running an awful lot. I've updated it so that it only runs now as part of the settings filter, which seems like that's really all that is needed, as far as I can tell.

**Comment by robincornett** [comment]
Note: although the PR for #131 is actually branched off of this PR, the call to get the users list will not work in this branch because the `make_request` method in the API class is using a query_arg to add the authorization token instead of adding it as a header in the request. I could fix it here and I guess deal with the merge conflict potential for the other, or just leave it...I have confirmed that fixing it does get an actual list of users.

**Comment by ashleyfae** [comment]
I'm having trouble connecting to Slack at all. After the modal, I'm redirected to a URL with these query string parameters:

```
post_type: download
page: edd-settings
tab: extensions
section: edd-slack-settings
code: abcddfjwoeifw
state: 
```

So `code` is provided, and with a value. `state` is provided, but with no value.

That means this is failing: https://github.com/easydigitaldownloads/edd-slack/blob/issue/129/core/ssl-only/class-edd-slack-app-oauth-settings.php#L301

and so is this: https://github.com/easydigitaldownloads/edd-slack/blob/issue/129/core/ssl-only/class-edd-slack-app-oauth-settings.php#L302

Does no one else have this problem? :thinking:

**Comment by robincornett** [comment]
@ashleyfae try #134 ... that is the one @mihaijoldis keeps breaking, but I'm bypassing the `state` check in it and hiding the whole URL with an extra redirect. It still feels a little wonky but I'm not sure if that's me or the way things are set up.

**Review by ashleyfae — APPROVED** [review]
