### PR TITLE
Fix non-string needle warning

### LINKED ISSUE #109: Audit for Deprecated PHP code
PHP Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /dom28934/wp-content/plugins/
edd-slack/edd-slack.php on line 260

https://secure.helpscout.net/conversation/1257540526

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #109

### CODE REVIEW

File: edd-slack.php [hunk 1]
```diff
@@ -256,10 +256,10 @@ private function upgrade_routine() {
 			if ( ! $last_upgrade ) {
 				$last_upgrade = '1.0.0';
 			}
-			
-			if ( strpos( $last_upgrade, 'pending' !== false ) ) {
+
+			if ( false !== strpos( $last_upgrade, 'pending' ) ) {
```
Comment (cklosowski) [inline edd-slack.php:260]: This check seems like we should alter the logic, since it results in an empty `if` statement. I think we should just flip the logic and state that if the status IS `pending` then wrap the other statements within this check instead of leaving an if with an empty statement, with follow up `else if and else`

Comment (robincornett) [reply edd-slack.php]: That makes sense--this logic was confusing me. I _think_ I understand why the empty `if` was left there, but hopefully have reworked it now to be correct.
